def printK():
    print(" *   *")
    print(" *  * ")
    print(" * *  ")
    print(" **   ")
    print(" * *  ")
    print(" *  * ")
    print(" *   *")
    print("      ")
def printA():
    print("   *   ")
    print("  * *  ")
    print(" *   * ")
    print(" ***** ")
    print(" *   * ")
    print(" *   * ")
    print(" *   * ")
    print("       ")
print("----- print KAKA -----")
printK()
printA()
printK()
printA()
